### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by iamthen0nce** [jstefanop/apolloui#6]
So, I try building the UI with just the `yarn` command.

The log is long, but the first 'error' message is:

```
./../nan/nan_implementation_12_inl.h:105:32: error: no matching function for call to ‘v8::Function::New(v8::Isolate*&, void (&)(const v8::FunctionCallbackInfo<v8::Value>&), v8::Local<v8::Object>&)’
                           , obj));
```
Later on:
```
../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
```
```
../../nan/nan_object_wrap.h:124:26: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’
```

Finally:
```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/tmp/asdf/apolloui/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Linux 5.10.63-v7+
gyp ERR! command "/usr/bin/node" "/tmp/asdf/apolloui/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /tmp/asdf/apolloui/node_modules/node-sass
gyp ERR! node -v v12.22.8
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
```

Maybe it might help specifying which version of `node` is used, or if there are some missing prerequisites.

Also, is it correct that it uses `python2`?
Thanks in advance!

---

Actually, is building just the UI supported at all or is it supposed to only work within `apolloapi`?

**Comment by michelem09** [comment]
Try to use Node version 9

**Comment by iamthen0nce** [comment]
![image](https://user-images.githubusercontent.com/89947325/173260229-7f27b5b4-a8da-4105-9566-6a9350dbe0a9.png)

Please don't tell me installing this is the recommended solution to run this software....

**Comment by michelem09** [comment]
By now it's the only way, you won't be hacked or similar if you install that.
